name : react-ci-cd-docker

# setting up trigger event
on : 
  push :
    branches : [main]
  pull_request :
    branches: [main]

 # what to do when trigger event occurs   
jobs :
  build_and_push_to_gcr :
    runs-on : ubuntu-latest
        
    steps:    
    - uses: actions/checkout@v2

    - name: install gcloud cli
      uses: google-github-actions/setup-gcloud@v2
      with: 
        project_id: ${{secrets.GOOGLE_PROJECT}}
        
    - name: build and push image
      env : 
        GOOGLE_PROJECT : ${{secrets.GOOGLE_PROJECT}}
      run : |
        gcloud auth configure-docker us-east4-docker.pkg.dev
        docker build -t us-east4-docker.pkg.dev/ciphernutz/test-repo/react-img:latest .
        docker push us-east4-docker.pkg.dev/ciphernutz/test-repo/react-img:latest
