name : react-ci-cd-docker

# setting up trigger event
on : 
  push :
    branches : [main]
  pull_request :
    branches: [main]

 # what to do when trigger event occurs   
jobs :
  CI :
    runs-on : ubuntu-latest
        
    steps:    
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with: 
        username : ${{secrets.DOCKERHUB_USERNAME}}
        password : ${{secrets.DOCKERHUB_PASSWORD}}

    - name: setup docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push to DockerHub
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push : true
        tags : ${{secrets.DOCKERHUB_USERNAME}}/react-image:latest

  CD :   
    needs : CI   
    runs-on : ubuntu-latest
    steps :

    - uses: docker/login-action@v3
      with: 
        username : ${{secrets.DOCKERHUB_USERNAME}}
        password : ${{secrets.DOCKERHUB_PASSWORD}}

    - name: Run docker Image  
      run: |
        docker pull gautamdockerpro/react-image:latest
        docker run --name react-app -p 3000:3000 gautamdockerpro/react-image:latest 
        hostname -I