name : react-ci-cd-docker-gcp

# setting up trigger event
on : 
  push :
    branches : [main]
  pull_request :
    branches: [main]

 # what to do when trigger event occurs   
jobs :

  CI :
    runs-on : ubuntu-latest
        
    steps:    
    - uses: actions/checkout@v2
    
    - name: Google Cloud Auth
      uses: "google-github-actions/auth@v2"
      with:
        credentials_json: '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}'
        project_id : ${{secrets.GOOGLE_PROJECT}}

    - name: install gcloud cli
      uses: google-github-actions/setup-gcloud@v2
      with: 
        project_id: ${{secrets.GOOGLE_PROJECT}}
        service_account_key: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        
    - name: "Use gcloud CLI"
      run: "gcloud info"    
        
    - name: build and push image
      env : 
        GOOGLE_PROJECT : ${{secrets.GOOGLE_PROJECT}}
        service_account_key: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        DOCKER_IMAGE_URL: us-east4-docker.pkg.dev/${{secrets.GOOGLE_PROJECT}}/test-repo/react-img:latest
      run : |
        gcloud auth configure-docker us-east4-docker.pkg.dev
        docker build -t ${{DOCKER_IMAGE_URL}} .
        docker push ${{DOCKER_IMAGE_URL}}

  CD :
    needs : CI
    runs-on : ubuntu-latest
    steps:    
    - name: Deploy to Cloud Run
      env :
        DOCKER_IMAGE_URL: us-east4-docker.pkg.dev/${{secrets.GOOGLE_PROJECT}}/test-repo/react-img:latest
      run: |
        gcloud run deploy react-app \
          --image ${{DOCKER_IMAGE_URL}} \
          --platform managed \
          --region us-east4 \
          --allow-unauthenticated    
     
