name : react-ci-cd-docker

# setting up trigger event
on : 
  push :
    branches : [main]
  pull_request :
    branches: [main]

 # what to do when trigger event occurs   
jobs :
  CI :
    runs-on : ubuntu-latest
        
    steps:    
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with: 
        username : ${{secrets.DOCKERHUB_USERNAME}}
        password : ${{secrets.DOCKERHUB_PASSWORD}}

    - name: setup docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push to DockerHub
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push : true
        tags : ${{secrets.DOCKERHUB_USERNAME}}/react-image:latest

  CD :   
    needs : CI
    runs-on : ubuntu-latest
    steps :
    - name : pull image and run on ec2
      uses : appleboy/ssh-action@master
      with : 
        host : ${{secrets.HOST_DNS}}
        username : ec2-user
        key :  ${{secrets.EC2_SSH_KEY}}
        envs : GITHUB_SHA
        script : |
          sudo yum update
          sudo yum install -y docker
          docker --version
          sudo service docker start
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | sudo docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          sudo docker pull ${{secrets.DOCKERHUB_USERNAME}}/react-image:latest
          sudo docker run --name react-app -p 3000:3000 gautamdockerpro/react-image:latest
          
