name : react-ci-cd

# setting up trigger event
on : 
  push :
    branches : [main]
  pull_request :
    branches: [main]

 # what to do when trigger event occurs   
jobs :
  build :
    runs-on : ubuntu-latest
    
    strategy :
      matrix :  
        node-version : [18.x]
        
    steps:    
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependency
      run: |
        yarn install
    - name: build  dependency.
      run: |
        npm run build
    - name: Uploading Build Artifact
      uses: actions/upload-artifact@v3
      with:
          name: build artifact
          path: ./build

  deploy :
    needs : build
    runs-on : ubuntu-latest
    steps:
    - name : Deploying to github page
      run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin `https://${{secrets.SECRET_KEY}}@github.com/Gautam70502/react-starter.git`
          npm run deploy
      env:
          user_name: 'Gautam70502'
          user_email: 'gautamrathod70502@gmail.com'
          github_token: ${{ secrets.SECRET_KEY }}
          repository: ${{github.repository}}
          
      
          
