name : react-ci-cd-docker

# setting up trigger event
on : 
  push :
    branches : [main]
  pull_request :
    branches: [main]

 # what to do when trigger event occurs   
jobs :
  CI :
    runs-on : ubuntu-latest
        
    steps:    
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with: 
        username : ${{secrets.DOCKERHUB_USERNAME}}
        password : ${{secrets.DOCKERHUB_PASSWORD}}

    - name: setup docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push to DockerHub
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push : true
        tags : ${{secrets.DOCKERHUB_USERNAME}}/react-image:latest

  CD :   
    needs : CI   
    runs-on : ubuntu-latest
    steps :

    - uses: actions/checkout@v2
    - name: view files
      run: ls -la /home/runner/
    - name: Deploy to EC2 Instance
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        TARGET: home
      run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ec2-user@${REMOTE_HOST}
            sudo apt update
            sudo apt install -y docker
            sudo service docker start
            sudo docker login --username ${{secrets.DOCKERHUB_USERNAME}} $ password: ${{secrets.DOCKERHUB_PASSWORD}}
            sudo docker pull ${{secrets.DOCKERHUB_USERNAME}}/react-image:latest
            sudo docker run --name react-app -p 3000:3000 gautamdockerpro/react-image:latest
